name: Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  kerja:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: langkah
        run: bash jalan.sh
        env:
          KUNCI_PROVIDER: ${{ secrets.KUNCI_PROVIDER }}
          CF_ACCOUNT: ${{ secrets.CF_ACCOUNT }}
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          CF_DB_UUID: ${{ secrets.CF_DB_UUID }}
